# Generated by scripts/build-formula.sh — do not edit by hand.
class Fossc < Formula
  desc "FOSS Club KIET operational handbook and gateway — terminal gazette"
  homepage "https://github.com/VanshSahay/fossc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_arm64.tar.gz"
      sha256 "73c915c5bef6fbb3818a383960eaedd5589bd1febfc10d74b4aebd14721f2ce1"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_amd64.tar.gz"
      sha256 "5524e1d100f3db71c9c6823d683ce2c8893c2f7c09bb996f5ed860e9734c5f69"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_arm64.tar.gz"
      sha256 "6347af0da59a44c4d0ba439f333ea665a262f7127e4c3c2f69604151621cc887"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_amd64.tar.gz"
      sha256 "3b05d966feff79868acc2a1de81b625a1ba6bca04768a58d526249b5ae2ebaf9"
    end
  end

  def install
    bin.install "fossc"
    man1.install "fossc.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fossc --version")
  end
end
