# Generated by scripts/build-formula.sh — do not edit by hand.
class Fossc < Formula
  desc "FOSS Club KIET operational handbook and gateway — terminal gazette"
  homepage "https://github.com/VanshSahay/fossc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_arm64.tar.gz"
      sha256 "b174e4ce09dd1a752bb742b6052002b7d674ecab37ee6a1e34749ee5ff33a8eb"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_amd64.tar.gz"
      sha256 "1990fd6703b0761881f7ed5909cd164ffc34865a13f1f8105167cad5f220e6bf"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_arm64.tar.gz"
      sha256 "fef1e2f4e6a57892ca9e189838a6438a8413b60faffdcc875303fbbfb62ec6bb"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_amd64.tar.gz"
      sha256 "8fc233ef1bba9aa4978e7f5e4cf2365599abfb6f4a9fdc94d0748ebd63dacb2d"
    end
  end

  def install
    bin.install "fossc"
    man1.install "fossc.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fossc --version")
  end
end
