# Generated by scripts/build-formula.sh — do not edit by hand.
class Fossc < Formula
  desc "FOSS Club KIET operational handbook and gateway — terminal gazette"
  homepage "https://github.com/VanshSahay/fossc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_arm64.tar.gz"
      sha256 "d0da088eebed1b9b0839d540a3c6f15e0b64a161a55c0770b676a5d6339f68f3"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_darwin_amd64.tar.gz"
      sha256 "7f3230d2b64029c4e17d9170c37e2ea37e46c69564dff0177c5eaa5b250bac67"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_arm64.tar.gz"
      sha256 "55a47a9a2cfd721abbdd80ffe1f4a88e56a6a6ef45ed95c84d882b90afdb1e0e"
    else
      url "https://github.com/VanshSahay/fossc/releases/download/v1.0.0/fossc_1.0.0_linux_amd64.tar.gz"
      sha256 "c531d156df92a850304dd61b7631c3db273efb186cb3b1efca5a6620297af0b9"
    end
  end

  def install
    bin.install "fossc"
    man1.install "fossc.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fossc --version")
  end
end
